program: train.py
name: sweepX
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--wandb_sweep"
  - "--all"
  - "--quantizing"
  - "--testing"
  - "--variable=z"
  - "--dataloader_mode=sampling_nc"
  - "--file_name=datasets/dataset1.nc"
  - ${args}
method: grid
parameters:
 batch_size:
  values: [4, 8, 12]
 model_precision:
  values: [16, 32]
 nepoches:
  values: [30, 40]
 nfeature:
  values: [128, 256]
 width:
  values: [256]